# Generated by Django 3.1.2 on 2020-10-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('rec_positon', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('province', models.CharField(max_length=500)),
                ('zip_code', models.CharField(max_length=200)),
                ('apply_position', models.CharField(max_length=500)),
            ],
        ),
    ]
