# Generated by Django 3.1.2 on 2020-10-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLForm', '0002_recruiter_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='dateto',
            field=models.CharField(default='Friday, October 8th, 2020', max_length=500),
        ),
    ]
